title: Fabrice Bernhard
baseURL: /
params:
  description: Fabrice Bernhard - my thoughts on why we need more geeks in society, how to make it happen... or often just my own geek thoughts.
  layout_style: grid
  palette: black
  header:
    type: header
    template: header
    title: Fabrice Bernhard
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: About
        url: /about
        style: link
  footer:
    type: footer
    template: footer
    content: >-
      &copy; Fabrice Bernhard, all rights reserved. This Hugo site was created on <a
      href="https://www.stackbit.com" target="_blank"
      rel="noopener">Stackbit</a>.
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/fabriceb'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/fabriceb'
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/in/fabricebernhard/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - type: action
        template: action
        label: DEV
        url: 'https://dev.to/fabriceb'
        style: icon
        icon_class: fa-dev
        new_window: true
    has_subscribe: false
    subscribe_title: Subscribe for new updates
    subscribe_content: >-
      Subscribe to my email newsletter to receive useful articles and special
      offers. This monthly email is sent out on the first of every month.
    subscribe_action: /subscribe-success
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
